site_name: GEE Courses

site_url: https://courses.geemap.org

repo_url: https://github.com/giswqs/GEE-Courses

theme:
  palette:
    scheme: preference
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
  custom_dir: "docs/overrides"

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      execute: False

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

extra:
  analytics:
    provider: google
    property: UA-186406134-1

nav:
  - Home: index.md
  - GEE Intro:
      - Image:
          - gee_intro/Image/image_visualization.ipynb
          - gee_intro/Image/image_metadata.ipynb
          - gee_intro/Image/image_overview.ipynb
          - gee_intro/Image/math_operations.ipynb
          - gee_intro/Image/conditional_operations.ipynb
          - gee_intro/Image/image_colorbar.ipynb
      - Image Collection:
          - gee_intro/ImageCollection/image_collection_overview.ipynb
          - gee_intro/ImageCollection/reducing_image_collection.ipynb
          - gee_intro/ImageCollection/mapping_over_image_collection.ipynb
          - gee_intro/ImageCollection/cloud_free_composite.ipynb
          - gee_intro/ImageCollection/visualizing_time_series.ipynb
      - Feature Collection:
          - gee_intro/FeatureCollection/vector_styling.ipynb
      - Asset Management:
          - gee_intro/AssetManagement/export_data.ipynb
          - gee_intro/AssetManagement/extract_values.ipynb
      - Analysis:
          - gee_intro/Analysis/zonal_statistics.ipynb
          - gee_intro/Analysis/zonal_stats_by_group.ipynb
  - Geemap Intro:
      - geemap_intro/01_introduction.md
      - geemap_intro/02_installation.md
      - geemap_intro/03_creating_maps.ipynb
      - geemap_intro/04_using_basemaps.ipynb
      - geemap_intro/05_gee_datasets.ipynb
      - geemap_intro/06_inspector_and_plotting.ipynb
      - geemap_intro/07_data_visualization.ipynb
      - geemap_intro/08_legend_and_colorbar.ipynb
      - geemap_intro/09_split_map.ipynb
      - geemap_intro/10_ts_inspector.ipynb
      - geemap_intro/11_statistics.ipynb
  - Geemap Complete:
      - Introduction:
          - geemap_complete/introduction/template.ipynb
      - Creating Maps:
          - geemap_complete/maps/template.ipynb
      - Datasets:
          - geemap_complete/datasets/template.ipynb
      - Visualization:
          - geemap_complete/visualization/template.ipynb
      - Analysis:
          - geemap_complete/analysis/template.ipynb
      - Data Export:
          - geemap_complete/export/template.ipynb
      - Web Apps:
          - geemap_complete/webapps/template.ipynb
      - Appliations:
          - geemap_complete/applications/template.ipynb
  - Blog: https://blog.gishub.org
  - YouTube Channel: https://www.youtube.com/c/QiushengWu
  - Report Issues: https://github.com/giswqs/GEE-Courses/issues
  - Ask Questions: https://github.com/giswqs/GEE-Courses/discussions
