site_name: GEE Courses

site_url: https://courses.geemap.org

repo_url: https://github.com/giswqs/GEE-Courses

theme:
  palette:
    scheme: preference
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
  custom_dir: "docs/overrides"

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: False
      execute: True

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

extra:
  analytics:
    provider: google
    property: UA-186406134-1

nav:
  - Home: index.md
  - GEE Intro:
      - Image:
          - gee_intro/Image/image_visualization.ipynb
          - gee_intro/Image/image_metadata.ipynb
          - gee_intro/Image/image_overview.ipynb
          - gee_intro/Image/math_operations.ipynb
          - gee_intro/Image/conditional_operations.ipynb
          - gee_intro/Image/image_colorbar.ipynb
      - Image Collection:
          - gee_intro/ImageCollection/image_collection_overview.ipynb
          - gee_intro/ImageCollection/reducing_image_collection.ipynb
          - gee_intro/ImageCollection/mapping_over_image_collection.ipynb
          - gee_intro/ImageCollection/cloud_free_composite.ipynb
          - gee_intro/ImageCollection/visualizing_time_series.ipynb
      - Feature Collection:
          - gee_intro/FeatureCollection/vector_styling.ipynb
      - Asset Management:
          - gee_intro/AssetManagement/export_data.ipynb
          - gee_intro/AssetManagement/extract_values.ipynb
      - Analysis:
          - gee_intro/Analysis/zonal_statistics.ipynb
          - gee_intro/Analysis/zonal_stats_by_group.ipynb
  - Geemap Intro:
      - geemap_intro/1_introduction.md
      - geemap_intro/2_installation.md
      - geemap_intro/3_creating_maps.ipynb
      - geemap_intro/4_using_basemaps.ipynb
      - geemap_intro/5_gee_datasets.ipynb
  - Blog: https://blog.gishub.org
  - YouTube Channel: https://www.youtube.com/c/QiushengWu
  - Report Issues: https://github.com/giswqs/GEE-Courses/issues
  - Ask Questions: https://github.com/giswqs/GEE-Courses/discussions
